site_name: BioCypher Ecosystem
site_url: https://biocypher.org
repo_url: https://github.com/biocypher/biocypher
repo_name: biocypher/biocypher

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - content.action.edit
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - BioCypher: "!include ./biocypher/mkdocs.nav.yml"
  - BioChatter: "!include ./biochatter/mkdocs.nav.yml"

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [., biocypher, biochatter]
  - monorepo
  - table-reader
  - mkdocs-jupyter
  - social
  - redirects:
      redirect_maps: {} # Can be configured as needed

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - neoteroi.timeline
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3
      title: On this page

extra:
  social:
    - icon: simple/zulip
      link: https://biocypher.zulipchat.com/
    - icon: material/contacts
      link: https://saezlab.org/
  version:
    provider: mike

extra_css:
  - assets/css/css-v1.1.0.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - scripts/tablesort.js

copyright: © Copyright 2021-2025, BioCypher developers.
